import { ASTNode, ASTNodeType, ByteCode, OpCode } from '../types';
import { CFGBuilder } from './cfg_builder';
import { Linearizer } from './linearizer';

/**
 * 编译器 - 将 AST 编译为字节码
 */
export class Compiler {
  compile(ast: ASTNode): ByteCode {
    if (ast.type !== ASTNodeType.PROGRAM) {
      throw new Error(`Expected Program node, got ${ast.type}`);
    }

    const builder = new CFGBuilder();
    const cfg = builder.build(ast);

    const linearizer = new Linearizer();
    const bc = linearizer.linearize(
      cfg,
      builder.getConstants(),
      builder.getNames(),
      builder.getVarnames(),
      0,
      [],
      builder.getGlobals(),
      builder.getNonlocals()
    );
    if (process.env['DEBUG_BYTECODE']) {
      console.log('Generated bytecode instructions:', bc.instructions.map(i => `${OpCode[i.opcode]} ${i.arg ?? ''}`));
      console.log('Generated names:', bc.names);
    }
    return bc;
  }
}
